CREATE TABLE EMPRESA (
    ID_EMPRESA SERIAL primary key,
    RAZON_SOCIAL varchar(60) NOT NULL,
    NIT_EMPRESA varchar(12) NOT NULL,
    DIR_EMPRESA varchar(80) NOT NULL,
    CORREO_EMPRESA varchar(90) NOT NULL,
    REPRESENTANTE varchar(90) NOT NULL,
    TELEFONO_EMPRESA varchar(12) NOT NULL
);

CREATE TABLE PAIS (
    ID_PAIS SERIAL primary key,
    NOMBRE_PAIS varchar(40) NOT NULL
);

CREATE TABLE DEPARTAMENTO (
    ID_DPTO SMALLINT primary key,
    NOMBRE_DPTO varchar(80) NOT NULL,
    ID_PAIS smallint NOT NULL,
    FOREIGN KEY (ID_PAIS)
        REFERENCES PAIS(ID_PAIS)
);

CREATE TABLE CIUDAD (
    ID_CIUDAD int primary key,
    NOMBRE_CIUDAD varchar(80) NOT NULL,
    ID_DPTO smallint NOT NULL,
    FOREIGN KEY (ID_DPTO)
        REFERENCES DEPARTAMENTO(ID_DPTO)
);

CREATE TABLE TIPO_PROYECTO (
    ID_TIPO_PROYECTO SERIAL primary key,
    NOMBRE_TIPO_PROYECTO varchar(80) NOT NULL,
    ESTADO_TIPO_PROYECTO varchar(1) NOT NULL
);

CREATE TABLE PROYECTO (
    ID_PROYECTO SERIAL primary key,
    NOMBRE_PROYECTO varchar(100) NOT NULL,
    ID_TIPO_PROYECTO smallint NOT NULL,
    VALOR_DESDE bigint DEFAULT 0,
    ESTADO_PROYECTO char(1) NOT NULL,
    ID_CIUDAD int NOT NULL,
    DIR_PROYECTO varchar(90) NOT NULL,
    FOREIGN KEY (ID_CIUDAD)
        REFERENCES CIUDAD(ID_CIUDAD),
    FOREIGN KEY (ID_TIPO_PROYECTO)
        REFERENCES TIPO_PROYECTO(ID_TIPO_PROYECTO)
);


CREATE TABLE TIPO_INMUEBLE (
    ID_TIPO_INMUEBLE SERIAL primary key,
	NUM_HABITACIONES char(2),
	NUM_BANOS char(2),
	TIENE_DEPOSITO char(1),
	NUM_GARAJES smallint DEFAULT 0,
    AREA_CONSTRUIDA float NOT NULL,
	AREA_PRIVADA float NOT NULL,
	PRECIO_DESDE bigint DEFAULT 0
);

CREATE TABLE TIPO_DOCUMENTO (
    ID_DOCUMENTO smallint primary key,
    NOMBRE_DOCUMENTO varchar(60) NOT NULL
);

CREATE TABLE CLIENTE (
    ID_CLIENTE SERIAL primary key,
	NUM_IDENTIFICACION varchar(15) NOT NULL,
	TIPO_DOCUMENTO smallint NOT NULL,
	PAPELLIDO_CLIENTE varchar(45) NOT NULL,
	SAPELLIDO_CLIENTE varchar(45) DEFAULT NULL,
	PNOMBRE_CLIENTE varchar(45) NOT NULL,
	SNOMBRE_CLIENTE varchar(45) DEFAULT NULL,
	DIR_CLIENTE varchar(80) NOT NULL,
	ID_CIUDAD int NOT NULL,
	FECHA_NACIMIENTO date,
	CORREO_ELECTRONICO varchar(90) DEFAULT NULL,
	INGRESO_MENSUAL bigint DEFAULT 0,
    TELEFONO_CLIENTE varchar(10) NOT NULL,
	FOREIGN KEY (TIPO_DOCUMENTO)
        REFERENCES TIPO_DOCUMENTO(ID_DOCUMENTO),
	FOREIGN KEY (ID_CIUDAD)
        REFERENCES CIUDAD(ID_CIUDAD)
);

CREATE TABLE INMUEBLE (
 ID_INMUEBLE INT primary key,
	ID_PROYECTO int NOT NULL,
	ID_TIPO_INMUEBLE smallint NOT NULL,
	NUM_TORRE varchar(2),
	NUM_INMUEBLE varchar(4),
	ID_CLIENTE int NOT NULL,
	PRECIO_VENTA bigint DEFAULT 0,
	COSTO_ADICIONAL bigint DEFAULT 0,
	FECHA_NEGOCIACION date,
	VALOR_SEPARACION bigint DEFAULT 0,
	NUM_CUOTAS smallint DEFAULT 0,
	ESTADO_INMUEBLE varchar(1),
	FOREIGN KEY (ID_PROYECTO)
        REFERENCES PROYECTO(ID_PROYECTO),
	FOREIGN KEY (ID_TIPO_INMUEBLE)
        REFERENCES TIPO_INMUEBLE(ID_TIPO_INMUEBLE),
	FOREIGN KEY (ID_CLIENTE)
        REFERENCES CLIENTE(ID_CLIENTE)
);

CREATE TABLE PARAMETRO_GENERAL (
    ID_PARAMETRO_GENERAL SERIAL primary key,
    NOMBRE_PARAMETRO varchar(10) NOT NULL,
    DESCRIPCION_PARAMETRO varchar(60) NOT NULL,
    VALOR_PARAMETRO varchar(100) NOT NULL,
    TIPO_PARAMETRO char(1) NOT NULL
);

CREATE TABLE RECAUDO (
ID_RECAUDO bigint NOT NULL,
ID_CLIENTE int NOT NULL,
ID_INMUEBLE smallint NOT NULL,
VALOR_RECAUDO bigint DEFAULT 0,
FECHA_NEGOCIACION date,
FOREIGN KEY (ID_CLIENTE)
    REFERENCES CLIENTE (ID_CLIENTE),
FOREIGN KEY (ID_INMUEBLE)
    REFERENCES INMUEBLE (ID_INMUEBLE)
);

CREATE TABLE AUDITORIA (
     ID_AUDITORIA BIGSERIAL primary key,
     USUARIO_AUDITORIA varchar(10) NOT NULL,
     EVENTO_AUDITORIA varchar(15) NULL,
	 TABLA_AUDITORIA varchar(15) NOT NULL,
	 ID_TABLA_AUDITORIA bigint NOT NULL,
	 IP_AUDITORIA varchar(15) NOT NULL,
	 FECHA_AUDITORIA date
);


CREATE TABLE PARAMETRO_NOMINA(
    ID_PARAMETRO_NOMINA SMALLINT PRIMARY KEY,
    DESCRIPCION_PARAMETRO VARCHAR(60) NOT NULL,
    VALOR_PARAMETRO SMALLINT NOT NULL
);

CREATE TABLE DEPENDENCIA(
    ID_DEPENDENCIA SMALLINT NOT NULL PRIMARY KEY,
    DESCRIPCION_DEPEND VARCHAR(40) NOT NULL
);

CREATE TABLE PENSION(
    ID_PENSION SMALLINT NOT NULL PRIMARY KEY ,
    DESCRIPCION_PNSION VARCHAR(60) NOT NULL
);

CREATE TABLE EPS(
    ID_EPS SMALLINT NOT NULL PRIMARY KEY,
    DESCRIPCION_EPS VARCHAR(60) NOT NULL
);

CREATE TABLE ARL(
    ID_ARL SMALLINT NOT NULL PRIMARY KEY,
    DESCRIPCION_ARL VARCHAR(60) NOT NULL
);

CREATE TABLE CARGO(
    ID_CARGO INT NOT NULL PRIMARY KEY,
    DESCRIPCION_CARGO VARCHAR(60) NOT NULL,
    ID_DEPENDENCIA SMALLINT NOT NULL,
    FOREIGN KEY (ID_DEPENDENCIA)
        REFERENCES DEPENDENCIA (ID_DEPENDENCIA)
);

CREATE TABLE TIPO_CONTRATO(
    ID_TIPO_CONTRATO SMALLINT PRIMARY KEY,
    DESCRIPCION_TPC VARCHAR(60) NOT NULL
);

CREATE TABLE EMPLEADO (
    ID_EMPLEADO INT NOT NULL,
	PNOMBRE_EMPLEADO varchar(45) NOT NULL,
	SNOMBRE_EMPLEADO varchar(45) DEFAULT NULL,
	PAPELLIDO_EMPLEADO varchar(45) NOT NULL,
	SAPELLIDO_EMPLEADO varchar(45) DEFAULT NULL,
	FECHA_INGRESO date NOT NULL,
	SUELDO_DEVENGADO INT NOT NULL,
	TRANSPORTE INT,
	NUM_DIAS_TRABAJADOS SMALLINT DEFAULT 30,
    ID_CARGO INT NOT NULL,
    ID_EPS SMALLINT NOT NULL,
    ID_ARL SMALLINT NOT NULL,
    ID_PENSION SMALLINT NOT NULL,
    ID_TIPO_CONTRATO SMALLINT NOT NULL,
    FOREIGN KEY (ID_CARGO)
        REFERENCES CARGO (ID_CARGO),
    FOREIGN KEY (ID_EPS)
        REFERENCES EPS (ID_EPS),
    FOREIGN KEY (ID_ARL)
        REFERENCES ARL (ID_ARL),
    FOREIGN KEY (ID_PENSION)
        REFERENCES PENSION (ID_PENSION),
    FOREIGN KEY (ID_TIPO_CONTRATO)
        REFERENCES TIPO_CONTRATO (ID_TIPO_CONTRATO),
    PRIMARY KEY (ID_EMPLEADO)
);

CREATE TABLE TIPO_NOVEDAD(
    ID_TIPO_NOVEDAD SMALLINT PRIMARY KEY,
    DESCRIPCION VARCHAR(60) NOT NULL,
    ID_PARAMETRO_NOMINA SMALLINT NOT NULL,
    FOREIGN KEY (ID_PARAMETRO_NOMINA)
        REFERENCES PARAMETRO_NOMINA (ID_PARAMETRO_NOMINA)
);

CREATE TABLE AUSENCIA(
    ID_AUSENCIA BIGSERIAL PRIMARY KEY,
    DIAS_AUSENCIA SMALLINT NOT NULL,
    FECHA_INICIO DATE NOT NULL,
    FECHA_FIN DATE NOT NULL
);

CREATE TABLE BONIFICACION(
    ID_BONIFICACION SERIAL PRIMARY KEY,
    DESCRIPCION_BNFCION VARCHAR(100),
    VALOR_BONIFICACION INT NOT NULL,
    ID_EMPLEADO INT NOT NULL,
    FOREIGN KEY (ID_EMPLEADO)
        REFERENCES EMPLEADO (ID_EMPLEADO)
);

CREATE TABLE NOVEDAD(
    ID_NOVEDAD BIGSERIAL PRIMARY KEY,
    ID_EMPLEADO INT NOT NULL,
    ID_TIPO_NOVEDAD SMALLINT NOT NULL,
    ID_AUSENCIA BIGSERIAL NOT NULL,
    FOREIGN KEY (ID_EMPLEADO)
        REFERENCES EMPLEADO (ID_EMPLEADO),
    FOREIGN KEY (ID_TIPO_NOVEDAD)
        REFERENCES TIPO_NOVEDAD (ID_TIPO_NOVEDAD),
    FOREIGN KEY (ID_AUSENCIA)
        REFERENCES AUSENCIA (ID_AUSENCIA)
);